name: On pull request

on:
  pull_request:

jobs:
  get_flutter_version:
    if: github.repository == 'surfstudio/surf-flutter-app-template'
    uses: surfstudio/flutter-ci-workflows/.github/workflows/get_flutter_version.yml@main

  analysis:
    needs: get_flutter_version
    uses: ./.github/workflows/analysis.yml
    with:
      FLUTTER_VERSION: ${{ needs.get_flutter_version.outputs.FLUTTER_VERSION }}

  testing:
    needs: [analysis, get_flutter_version]
    uses: surfstudio/flutter-ci-workflows/.github/workflows/testing.yml@main
    with:
      FLUTTER_VERSION: ${{ needs.get_flutter_version.outputs.FLUTTER_VERSION }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

